# Ubuntu 18.04 with Java 8 installed

FROM ubuntu:18.04
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y less software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
	apt-get install oracle-java8-set-default && \
	apt-get install unzip && \
    apt-get clean

ADD trade.volume.monitoring.service-0.0.1.zip .
RUN unzip -q trade.volume.monitoring.service-0.0.1.zip && \
    rm trade.volume.monitoring.service-0.0.1.zip && \
    mv trade.volume.monitoring.service-* trade.volume.monitoring.service && \
    chmod +x trade.volume.monitoring.service/bin/start.sh && \
    chmod +x trade.volume.monitoring.service/bin/stop.sh && \
    sed -i -e 's/\r$//' trade.volume.monitoring.service/bin/start.sh && \
    sed -i -e 's/\r$//' trade.volume.monitoring.service/bin/stop.sh

EXPOSE 8091

ENTRYPOINT ["/trade.volume.monitoring.service/bin/start.sh"]
CMD ["--console"]